### ISSUE TITLE
[ques]很好奇是怎么解决防盗版的

### ISSUE THREAD

**Issue by timelic** [Sucty/Fuck-qidian-drm#1]
是手写了爬虫来爬么，怎么解决反盗版的混淆的呢

**Comment by Sucty** [comment]
OCR

**Comment by timelic** [comment]
> OCR

用的是哪个OCR呢？感觉有些OCR准确率不够高

**Comment by Sucty** [comment]
PC端QQ截图后，直接点文字识别，但排版很糟糕，需要自己调整

**Comment by timelic** [comment]
明白了。我之前曾经想用nodejs加ocr来做爬虫，后面还是被ocr这困住了。免费高质量的OCR的API几乎没有，开源的话又不太想配。
